#!/bin/sh

jpeg_display()
{
    while true
    do
        if [ -e "/dev/fb0" ]; then
            break
        fi
        sleep 0.02
    done

    theme="creality"
    width=$(get_fb_info.sh width)
    height=$(get_fb_info.sh height)
    model=$(get_sn_mac.sh model)

    case $model in
        "CR-10 H1")
            logofile=${theme}_portrait_rot0_${width}x${height}.jpg
            ;;

        "CR-K1")
            logofile=${theme}_landscape_rot180_${width}x${height}.jpg
            ;;

        "CR-K1 Max")
            logofile=${theme}_landscape_rot180_${width}x${height}.jpg
            ;;

        "Nebula Pad")
            logofile=${theme}_portrait_rot270_${width}x${height}.jpg
            [ -e /usr/bin/boot_display ] && [ -e /etc/boot-display-nebula ] && /usr/bin/boot_display boot /etc/boot-display-nebula/ &
            ;;

        *)
            logofile=test.jpeg
            ;;

    esac

    cmd_jpeg_display /etc/logo/$logofile
}

case "$1" in
    start)
        jpeg_display &

    ;;
    *)
        exit 1
esac

exit 0
