#!/bin/sh

jpeg_display()
{
    while true
    do
        if [ -e "/dev/fb0" ]; then
            break
        fi
        sleep 0.02
    done

    theme="creality"
    width=$(get_fb_info.sh width)
    height=$(get_fb_info.sh height)
    model=$(get_sn_mac.sh model)

    case $model in
        "CR-10 H1")
            logofile=${theme}_portrait_rot0_${width}x${height}.jpg
            ;;

        "CR-K1")
            logofile=${theme}_landscape_rot180_${width}x${height}.jpg
            ;;

        "CR-K1 Max")
            logofile=${theme}_landscape_rot180_${width}x${height}.jpg
            ;;

        "Nebula Pad")
            logofile=${theme}_portrait_rot270_${width}x${height}.jpg
            path=/etc/boot-display-nebula/part
            width=480
            height=272
            ;;

        "F003")
            logofile=${theme}_portrait_rot270_${width}x${height}.jpg
            path=/etc/boot-display-nebula/part
            width=480
            height=272
            ;;

        *)
            logofile=test.jpeg
            ;;

    esac

    cmd_jpeg_display /etc/logo/$logofile
    if [ "x$model" = "xF003" -o "x$model" = "xNebula Pad" ]; then
        [ ! -d /usr/data/creality/boot_display ] && mkdir -p /usr/data/creality/boot_display
        [ ! -s /usr/data/creality/boot_display/boot_display0.yuv ] || [ ! -s /usr/data/creality/boot_display/boot_display1.yuv ] && boot_display boot path=$path width=$width height=$height
        boot_display display width=$width height=$height num1=$(ls /etc/boot-display-nebula/part0 | wc -l) num2=$(ls /etc/boot-display-nebula/part1 | wc -l) &
    fi
}

case "$1" in
    start)
        jpeg_display &

    ;;
    *)
        exit 1
esac

exit 0
